app/Http/routes.php
<?php
/**
Event::listen('illuminate.query', function($query)
{
    var_dump($query);
});
 * 
 */
Route::group(['prefix' => 'lang', 'middleware' => ['locale']], function(){
  Route::get('{lang}', function($lang){
    Translation::setLocale($lang);
    $previous = URL::previous();
    $new = preg_replace('/(\.[a-z]{2,5})(\/[a-z]{0,2})?\//', "$1/".$lang."/", $previous);
    return Redirect::to($new);
});      
});

Route::group(['prefix' => Translation::getRoutePrefix(), 'middleware' => ['locale']], function()
{
    Route::group(['middleware' => 'auth'], function ()
	{
        Route::group([
			'middleware' => 'access.routeNeedsRoleOrPermission',
			'role'       => ['Administrator'],
			'permission' => ['view_backend'],
			'redirect'   => '/',
			'with'       => ['flash_danger', 'You do not have access to do that.']
		], function ()
		{
        Route::get('download/{file}', function($file){ 
            $file_path = storage_path() .'/'. $file;//dd($file_path);
            if (file_exists($file_path))
            {
                // Send Download
                $filename = preg_filter('/[^\d\w\s \.]/', '_', $file);
                return Response::download($file_path, $filename, [
                    'Content-Length: '. filesize($file_path)
                ], 'attachment');
            }
            else
            {
                // Error
                exit('Requested file does not exist on our server!');
            }
        })->where(['file' => '(.*)']);
                });
        });
/**
 * Frontend Routes
 * Namespaces indicate folder structure
 */
Route::group(['namespace' => 'Frontend'], function ()
{
	require(__DIR__ . "/Routes/Frontend/Frontend.php");
	require(__DIR__ . "/Routes/Frontend/Access.php");
});

/**
 * Backend Routes
 * Namespaces indicate folder structure
 */
Route::group(['namespace' => 'Backend'], function ()
{
	Route::group(['prefix' => 'admin', 'middleware' => 'auth'], function ()
	{
		/**
		 * These routes need the Administrator Role
		 * or the view-backend permission (good if you want to allow more than one group in the backend, then limit the backend features by different roles or permissions)
		 *
		 * If you wanted to do this in the controller it would be:
		 * $this->middleware('access.routeNeedsRoleOrPermission:{role:Administrator,permission:view_backend,redirect:/,with:flash_danger|You do not have access to do that.}');
		 *
		 * You could also do the above in the Route::group below and remove the other parameters, but I think this is easier to read here.
		 * Note: If you have both, the controller will take precedence.
		 */
		Route::group([
			'middleware' => 'access.routeNeedsRoleOrPermission',
			'role'       => ['Administrator'],
			'permission' => ['view_backend'],
			'redirect'   => '/',
			'with'       => ['flash_danger', 'You do not have access to do that.']
		], function ()
		{
			Route::get('dashboard', ['as' => 'backend.dashboard', 'uses' => 'DashboardController@index']);
                        Route::get('media', ['as' => 'backend.media', 'uses' => 'MediaController@index']);
			require(__DIR__ . "/Routes/Backend/Access.php");
		});
                /* Result Management */
                Route::group([
                        'middleware' => 'access.routeNeedsPermission',
                        'permission' => ['add_result'], 
                        'redirect'   => '/',
                        'with'       => ['flash_danger', 'You do not have access to do that.']
                ], function ()
                {                        

                    Route::get('language', ['as' => 'admin.language.index', 'uses' => 'LocalizationController@index']);
                    Route::post('language/import', ['as' => 'admin.language.import', 'uses' => 'LocalizationController@import']);
                    Route::match(['patch','put'],'language', ['as' => 'backend.language.update', 'uses' => 'LocalizationController@update']);

                });
                require(__DIR__ . "/Routes/Backend/Participant.php");
                require(__DIR__ . "/Routes/Backend/Project.php");
                require(__DIR__ . "/Routes/Backend/General.php");
	});
});

/**
 * Backend Routes
 * Namespaces indicate folder structure
 */
//Route::group(['namespace' => 'Ajax', 'middleware' => 'ajax'], function ()
Route::group(['namespace' => 'Ajax'], function ()
{
    require(__DIR__ . "/Routes/Ajax/Ajax.php");
});
});

app/Role.php
<?php namespace App;

use Illuminate\Support\Facades\DB;
use Illuminate\Database\Eloquent\Model;

/**
 * Class Role
 * @package App
 */
class Role extends Model {
	/**
	 * The database table used by the model.
	 *
	 * @var string
	 */
	protected $table;

	/**
	 *
	 */
	public function __construct()
	{
		$this->table = config('access.roles_table');
	}

	/**
	 * Many-to-Many relations with Users.
	 *
	 * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
	 */
	public function users()
	{
		return $this->hasMany(config('auth.model'), 'role_id');
	}

        
	/**
	 * Many-to-Many relations with Permission.
	 *
	 * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
	 */
	public function permissions()
	{
		return $this->belongsToMany(config('access.permission'), config('access.permission_role_table'), 'role_id', 'permission_id');
	}

	/**
	 * @return string
	 */
	public function getEditButtonAttribute() {
		return '<a href="'.route('admin.access.roles.edit', $this->id).'" class="btn btn-xs btn-primary"><i class="fa fa-pencil" data-toggle="tooltip" data-placement="top" title="Edit"></i></a>';
	}

	/**
	 * @return string
	 */
	public function getDeleteButtonAttribute() {
		if ($this->id != 1) //Cant delete master admin role
			return '<a href="'.route('admin.access.roles.destroy', $this->id).'" class="btn btn-xs btn-danger" data-method="delete"><i class="fa fa-times" data-toggle="tooltip" data-placement="top" title="Delete"></i></a>';
		return '';
	}

	/**
	 * @return string
	 */
	public function getActionButtonsAttribute() {
		return $this->getEditButtonAttribute().' '.$this->getDeleteButtonAttribute();
	}

	/**
	 * Before delete all constrained foreign relations
	 *
	 * @return bool
	 */
	public function beforeDelete()
	{
		DB::table(config('access.assigned_roles_table'))->where('role_id', $this->id)->delete();
		DB::table(config('access.permission_role_table'))->where('role_id', $this->id)->delete();
	}

	/**
	 * Save the inputted permissions.
	 *
	 * @param mixed $inputPermissions
	 *
	 * @return void
	 */
	public function savePermissions($inputPermissions)
	{
		if (! empty($inputPermissions)) {
			$this->permissions()->sync($inputPermissions);
		} else {
			$this->permissions()->detach();
		}
	}

	/**
	 * Attach permission to current role.
	 *
	 * @param object|array $permission
	 *
	 * @return void
	 */
	public function attachPermission($permission)
	{
		if (is_object($permission)) {
			$permission = $permission->getKey();
		}

		if (is_array($permission)) {
			$permission = $permission['id'];
		}

		$this->permissions()->attach($permission);
	}

	/**
	 * Detach permission form current role.
	 *
	 * @param object|array $permission
	 *
	 * @return void
	 */
	public function detachPermission($permission)
	{
		if (is_object($permission))
			$permission = $permission->getKey();

		if (is_array($permission))
			$permission = $permission['id'];

		$this->permissions()->detach($permission);
	}

	/**
	 * Attach multiple permissions to current role.
	 *
	 * @param mixed $permissions
	 *
	 * @return void
	 */
	public function attachPermissions($permissions)
	{
		foreach ($permissions as $permission) {
			$this->attachPermission($permission);
		}
	}

	/**
	 * Detach multiple permissions from current role
	 *
	 * @param mixed $permissions
	 *
	 * @return void
	 */
	public function detachPermissions($permissions)
	{
		foreach ($permissions as $permission) {
			$this->detachPermission($permission);
		}
	}
}

app/User.php
<?php namespace App;

use Illuminate\Auth\Authenticatable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Auth\Passwords\CanResetPassword;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Contracts\Auth\Authenticatable as AuthenticatableContract;
use Illuminate\Contracts\Auth\CanResetPassword as CanResetPasswordContract;
use App\Services\Access\Traits\UserHasOrganization;
use App\Services\Access\Traits\UserHasRole;
use Nicolaslopezj\Searchable\SearchableTrait;

/**
 * Class User
 * @package App
 */
class User extends Model implements AuthenticatableContract, CanResetPasswordContract {

	use Authenticatable, CanResetPassword, SoftDeletes, UserHasOrganization, UserHasRole, SearchableTrait;
        

	/**
	 * The database table used by the model.
	 *
	 * @var string
	 */
	protected $table = 'users';

	/**
	 * The attributes that are not mass assignable.
	 *
	 * @var array
	 */
	protected $guarded = ['id'];

	/**
	 * The attributes excluded from the model's JSON form.
	 *
	 * @var array
	 */
	protected $hidden = ['password', 'remember_token'];

	/**
	 * For soft deletes
	 *
	 * @var array
	 */
	protected $dates = ['deleted_at'];
        
        /**
        * Searchable rules.
        *
        * @var array
        */
        protected $searchable = [
           'columns' => [
               'name' => 2,
               'email' => 2,
           ],
        ];        

	/**
	 * @return \Illuminate\Database\Eloquent\Relations\HasMany
	 */
	public function providers() {
		return $this->hasMany('App\UserProvider');
	}
        
        /**
	 * @return \Illuminate\Database\Eloquent\Relations\HasMany
	 */
	public function medias() {
		return $this->hasMany('App\Media', 'owner_id');
	}
        
        /**
	 * @return \Illuminate\Database\Eloquent\Relations\HasMany
	 */
	public function results() {
		return $this->hasMany('App\Result', 'user_id');
	}

	/**
	 * Hash the users password
	 *
	 * @param $value
	 */
	public function setPasswordAttribute($value)
	{
		if (\Hash::needsRehash($value))
			$this->attributes['password'] = bcrypt($value);
		else
			$this->attributes['password'] = $value;
	}

	/**
	 * @return mixed
	 */
	public function canChangeEmail() {
		return config('access.users.change_email');
	}

	/**
	 * @return string
	 */
	public function getConfirmedLabelAttribute() {
		if ($this->confirmed == 1)
			return "<label class='label label-success'>Yes</label>";
		return "<label class='label label-danger'>No</label>";
	}
}

app/Http/Controllers/Backend/Access/OrganizationController.php
<?php

namespace App\Http\Controllers\Backend\Access;

use App\Http\Controllers\Controller;
use App\Http\Requests;
use App\Repositories\Backend\Organization\OrganizationContract;
use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\Response;

class OrganizationController extends Controller
{
    /**
	 * @var OrganizationRepositoryContract
	 */
	protected $organizations;

	/**
	 * @param OrganizationRepositoryContract $organizations
	 * @param PermissionRepositoryContract $permissions
	 */
	public function __construct(
		OrganizationContract $organizations) {
		$this->organizations = $organizations;
	}
    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        //
        return view('backend.access.organizations.index')
			->withOrganizations($this->organizations->getOrganizationsPaginated(50));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        //
        return view('backend.access.organizations.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  Request  $request
     * @return Response
     */
    public function store(Request $request)
    {
        $this->organizations->create($request->all());
		return redirect()->route('admin.access.organizations.index')->withFlashSuccess('The organization was successfully created.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function edit($organization)
    {
        //
        return view('backend.access.organizations.edit')
                    ->withOrganization($organization);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  Request  $request
     * @param  int  $id
     * @return Response
     */
    public function update(Request $request, $organization)
    {
        $this->organizations->update($organization, $request->all());
		return redirect()->route('admin.access.organizations.index')->withFlashSuccess('The organization was successfully created.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Backend/Access/PermissionController.php
<?php namespace App\Http\Controllers\Backend\Access;

use App\Http\Controllers\Controller;
use App\Repositories\Backend\Role\RoleRepositoryContract;
use App\Repositories\Backend\Permission\PermissionRepositoryContract;
use App\Http\Requests\Backend\Access\Permission\CreatePermissionRequest;
use App\Http\Requests\Backend\Access\Permission\UpdatePermissionRequest;

/**
 * Class PermissionController
 * @package App\Http\Controllers\Access
 */
class PermissionController extends Controller {

	/**
	 * @var RoleRepositoryContract
	 */
	protected $roles;
	/**
	 * @var PermissionRepositoryContract
	 */
	protected $permissions;

	/**
	 * @param RoleRepositoryContract $roles
	 * @param PermissionRepositoryContract $permissions
	 */
	public function __construct(
		RoleRepositoryContract $roles,
		PermissionRepositoryContract $permissions) {
		$this->roles = $roles;
		$this->permissions = $permissions;
	}

	/**
	 * @return mixed
	 */
	public function index() {
		return view('backend.access.roles.permissions.index')
			->withPermissions($this->permissions->getPermissionsPaginated(50));
	}

	/**
	 * @return mixed
	 */
	public function create() {
		return view('backend.access.roles.permissions.create')
			->withRoles($this->roles->getAllRoles());
	}

	/**
	 * @param CreatePermissionRequest $request
	 * @return mixed
	 */
	public function store(CreatePermissionRequest $request) {
		$this->permissions->create($request->except('permission_roles'), $request->only('permission_roles'));
		return redirect()->route('admin.access.roles.permissions.index')->withFlashSuccess("Permission successfully created.");
	}

	/**
	 * @param $id
	 * @return mixed
	 */
	public function edit($id) {
		$permission = $this->permissions->findOrThrowException($id, true);
		return view('backend.access.roles.permissions.edit')
			->withPermission($permission)
			->withPermissionRoles($permission->roles->lists('id')->all())
			->withRoles($this->roles->getAllRoles());
	}

	/**
	 * @param $id
	 * @param UpdatePermissionRequest $request
	 * @return mixed
	 */
	public function update($id, UpdatePermissionRequest $request) {
		$this->permissions->update($id, $request->except('permission_roles'), $request->only('permission_roles'));
		return redirect()->route('admin.access.roles.permissions.index')->withFlashSuccess("Permission successfully updated.");
	}

	/**
	 * @param $id
	 * @return mixed
	 */
	public function destroy($id) {
		$this->permissions->destroy($id);
		return redirect()->route('admin.access.roles.permissions.index')->withFlashSuccess("Permission successfully deleted.");
	}
}

app/Http/Controllers/Backend/DashboardController.php
<?php namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Repositories\Backend\Organization\OrganizationContract;
use App\Repositories\Backend\PLocation\PLocationContract;
use App\Repositories\Backend\Project\ProjectContract;

/**
 * Class DashboardController
 * @package App\Http\Controllers\Backend
 */
class DashboardController extends Controller {
    
        protected $organizations;

        protected $projects;

        protected $plocations;

        public function __construct(
         OrganizationContract $organizations,
         ProjectContract $projects,
         PLocationContract $plocations
         ) 
        {
            $this->organizations = $organizations;
            $this->projects = $projects;
            $this->plocations = $plocations;
        }
	/**
	 * @return \Illuminate\View\View
	 */
	public function index()
	{
            if(auth()->user()->can('manage_organization')){
                $orgs = $this->organizations->getAllOrganizations('name', 'asc');
            }else{
                $orgs[0] = auth()->user()->organization;
            }
            return view('backend.dashboard')
                   ->withOrgs($orgs);
	}
}

resources/views/backend/access/banned.blade.php
@extends ('backend.layouts.master')

@section ('title', 'User Management | Deactivated Users')

@section('page-header')
    <h1>
        User Management
        <small>Deactivated Users</small>
    </h1>
@endsection

@section ('breadcrumbs')
     <li><a href="{!!route('backend.dashboard')!!}"><i class="fa fa-dashboard"></i> Dashboard</a></li>
     <li>{!! link_to_route('admin.access.users.index', 'User Management') !!}</li>
     <li class="active">{!! link_to_route('admin.access.users.banned', 'Banned Users') !!}</li>
@stop

@section('content')
    @include('backend.access.includes.partials.header-buttons')

    <table class="table table-striped table-bordered table-hover">
        <thead>
        <tr>
            <th>ID</th>
            <th>Name</th>
            <th>E-mail</th>
            <th>Confirmed</th>
            <th>Roles</th>
            <th>Other Permissions</th>
            <th class="visible-lg">Created</th>
            <th class="visible-lg">Last Updated</th>
            <th>Actions</th>
        </tr>
        </thead>
        <tbody>
            @if ($users->count())
                @foreach ($users as $user)
                    <tr>
                        <td>{!! $user->id !!}</td>
                        <td>{!! $user->name !!}</td>
                        <td>{!! link_to("mailto:".$user->email, $user->email) !!}</td>
                        <td>{!! $user->confirmed_label !!}</td>
                        <td>
                            @if ($user->roles()->count() > 0)
                                @foreach ($user->roles as $role)
                                    {!! $role->name !!}<br/>
                                @endforeach
                            @else
                                None
                            @endif
                        </td>
                        <td>
                            @if ($user->permissions()->count() > 0)
                                @foreach ($user->permissions as $perm)
                                    {!! $perm->display_name !!}<br/>
                                @endforeach
                            @else
                                None
                            @endif
                        </td>
                        <td class="visible-lg">{!! $user->created_at->diffForHumans() !!}</td>
                        <td class="visible-lg">{!! $user->updated_at->diffForHumans() !!}</td>
                        <td>{!! $user->action_buttons !!}</td>
                    </tr>
                @endforeach
            @else
                <td colspan="9">No Banned Users</td>
            @endif
        </tbody>
    </table>

    <div class="pull-left">
        {!! $users->total() !!} user(s) total
    </div>

    <div class="pull-right">
        {!! $users->render() !!}
    </div>

    <div class="clearfix"></div>
@stop

resources/views/backend/access/deactivated.blade.php
@extends ('backend.layouts.master')

@section ('title', 'User Management | Deactivated Users')

@section('page-header')
    <h1>
        User Management
        <small>Deactivated Users</small>
    </h1>
@endsection

@section ('breadcrumbs')
     <li><a href="{!!route('backend.dashboard')!!}"><i class="fa fa-dashboard"></i> Dashboard</a></li>
     <li>{!! link_to_route('admin.access.users.index', 'User Management') !!}</li>
     <li class="active">{!! link_to_route('admin.access.users.deactivated', 'Deactivated Users') !!}</li>
@stop

@section('content')
    @include('backend.access.includes.partials.header-buttons')

    <table class="table table-striped table-bordered table-hover">
        <thead>
        <tr>
            <th>ID</th>
            <th>Name</th>
            <th>E-mail</th>
            <th>Confirmed</th>
            <th>Roles</th>
            <th>Other Permissions</th>
            <th class="visible-lg">Created</th>
            <th class="visible-lg">Last Updated</th>
            <th>Actions</th>
        </tr>
        </thead>
        <tbody>
            @if ($users->count())
                @foreach ($users as $user)
                    <tr>
                        <td>{!! $user->id !!}</td>
                        <td>{!! $user->name !!}</td>
                        <td>{!! link_to("mailto:".$user->email, $user->email) !!}</td>
                        <td>{!! $user->confirmed_label !!}</td>
                        <td>
                            @if ($user->roles()->count() > 0)
                                @foreach ($user->roles as $role)
                                    {!! $role->name !!}<br/>
                                @endforeach
                            @else
                                None
                            @endif
                        </td>
                        <td>
                            @if ($user->permissions()->count() > 0)
                                @foreach ($user->permissions as $perm)
                                    {!! $perm->display_name !!}<br/>
                                @endforeach
                            @else
                                None
                            @endif
                        </td>
                        <td class="visible-lg">{!! $user->created_at->diffForHumans() !!}</td>
                        <td class="visible-lg">{!! $user->updated_at->diffForHumans() !!}</td>
                        <td>{!! $user->action_buttons !!}</td>
                    </tr>
                @endforeach
            @else
                <td colspan="9">No Deactivated Users</td>
            @endif
        </tbody>
    </table>

    <div class="pull-left">
        {!! $users->total() !!} user(s) total
    </div>

    <div class="pull-right">
        {!! $users->render() !!}
    </div>

    <div class="clearfix"></div>
@stop

resources/views/backend/access/index.blade.php
@extends ('backend.layouts.master')

@section ('title', 'User Management')

@section('page-header')
    <h1>
        User Management
        <small>Active Users</small>
    </h1>
@endsection

@section ('breadcrumbs')
    <li><a href="{!!route('backend.dashboard')!!}"><i class="fa fa-dashboard"></i> Dashboard</a></li>
    <li class="active">{!! link_to_route('admin.access.users.index', 'User Management') !!}</li>
@stop

@section('content')
    @include('backend.access.includes.partials.header-buttons')
<div class="pull-left" style="margin-bottom:10px">
        <div class="row">
        {!! Form::open(['route' => 'admin.access.users.search', 'class' => 'form-horizontal', 'role' => 'form', 'method' => 'get']) !!}
        
        <div class='col-xs-12 col-sm-12 col-md-12 form-inline'>
            <div class="input-group">
                <input name="q" class="form-control" placeholder="{!! Input::get('q')? Input::get('q'):'Search' !!}" type="text">
                <span class="input-group-btn">
                    <button type="submit" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i></button>
                </span>
            </div>
        </div>
        
        {!! Form::close() !!}
        </div>
        
</div>    
{!! Form::open(['route' => 'admin.access.users.bulk', 'class' => 'form-horizontal', 'role' => 'form', 'method' => 'post']) !!}

<div class='row' style='margin-bottom: 10px'>
<!--div class='col-xs-12 col-sm-12 col-md-12 form-inline'>
 {!! Form::label('role', 'Change to - ', ['class' => 'control-label']) !!}
 {!! Form::select('role', isset($roles) ? $roles->lists('name','id'):['none' => 'None'],false, ['class' => 'form-control']) !!}

 {!! Form::submit( 'Bulk Change', ['class' => 'btn btn-secondary']) !!}
</div-->
</div>
    <table class="table table-striped table-bordered table-hover">
        <thead>
        <tr>
            <th><input type='checkbox' id='checkall' class='checkall checkbox'></th>
            <th>ID</th>
            <th>Name</th>
            <th>E-mail</th>
            <th>Confirmed</th>
            <th>Organizations</th>
            <th>Role</th>
            <th>Other Permissions</th>
            <th class="visible-lg">Created</th>
            <th class="visible-lg">Last Updated</th>
            <th>Actions</th>
        </tr>
        </thead>
        <tbody>
            @foreach ($users as $user)
                @if(access()->user()->can('manage_organization') || access()->user()->organization == $user->organization)
                <tr>
                    <td><input type='checkbox' class='checkall checkbox' name='users[{!! $user->id !!}]'></td>
                    <td>{!! $user->id !!}</td>
                    <td>
                        <img width="30" height="30" src="{!! (!empty($user->avatar)? $user->avatar: asset('img/backend/user2-160x160.png')) !!}" alt="{!! $user->name !!}" title="{!! $user->name !!}"> {!! $user->name !!}
                    </td>
                    <td>{!! link_to("mailto:".$user->email, $user->email) !!}</td>
                    <td>{!! $user->confirmed_label !!}</td>
                    <td>
                        @if ($user->organization()->count() > 0)
                            {!! $user->organization->name !!}
                        @else
                            None
                        @endif
                    </td>
                    <td>
                        @if ($user->role()->count() > 0)
                            
                                {!! $user->role->name !!}<br/>
                        @else
                            None
                        @endif
                    </td>
                    <td>
                        @if ($user->permissions()->count() > 0)
                            @foreach ($user->permissions as $perm)
                                {!! $perm->display_name !!}<br/>
                            @endforeach
                        @else
                            None
                        @endif
                    </td>
                    <td class="visible-lg">{!! $user->created_at->diffForHumans() !!}</td>
                    <td class="visible-lg">{!! $user->updated_at->diffForHumans() !!}</td>
                    <td>{!! $user->action_buttons !!}</td>
                </tr>
                @endif
            @endforeach
        </tbody>
    </table>

    <div class="pull-left">
        {!! $users->total() !!} user(s) total
    </div>

    <div class="pull-right">
        {!! $users->render() !!}
    </div>

    <div class="clearfix"></div>
    {!! Form::close() !!}
@stop

resources/views/backend/access/search.blade.php
@extends ('backend.layouts.master')

@section ('title', 'User Management')

@section('page-header')
    <h1>
        User Management
        <small>Active Users</small>
    </h1>
@endsection

@section ('breadcrumbs')
    <li><a href="{!!route('backend.dashboard')!!}"><i class="fa fa-dashboard"></i> Dashboard</a></li>
    <li class="active">{!! link_to_route('admin.access.users.index', 'User Management') !!}</li>
@stop

@section('content')
    @include('backend.access.includes.partials.header-buttons')
{!! Form::open(['route' => 'admin.access.users.bulk', 'class' => 'form-horizontal', 'role' => 'form', 'method' => 'post']) !!}
<div class='row'>
<div class='col-xs-12 col-sm-12 col-md-12 form-inline'>
 {!! Form::label('role', 'Change to - ', ['class' => 'control-label']) !!}
 {!! Form::select('role', isset($roles) ? $roles->lists('name','id'):['none' => 'None'],false, ['class' => 'form-control']) !!}

 {!! Form::submit( 'Bulk Change', ['class' => 'btn btn-secondary']) !!}
</div>
</div>
    <table class="table table-striped table-bordered table-hover">
        <thead>
        <tr>
            <th><input type='checkbox' id='checkall' class='checkall checkbox'></th>
            <th>ID</th>
            <th>Name</th>
            <th>E-mail</th>
            <th>Confirmed</th>
            <th>Roles</th>
            <th>Other Permissions</th>
            <th class="visible-lg">Created</th>
            <th class="visible-lg">Last Updated</th>
            <th>Actions</th>
        </tr>
        </thead>
        <tbody>
            @foreach ($users as $user)
                <tr>
                    <td><input type='checkbox' class='checkall checkbox' name='users[{!! $user->id !!}]'></td>
                    <td>{!! $user->id !!}</td>
                    <td>{!! $user->name !!}</td>
                    <td>{!! link_to("mailto:".$user->email, $user->email) !!}</td>
                    <td>{!! $user->confirmed_label !!}</td>
                    <td>
                        @if ($user->roles()->count() > 0)
                            @foreach ($user->roles as $role)
                                {!! $role->name !!}<br/>
                            @endforeach
                        @else
                            None
                        @endif
                    </td>
                    <td>
                        @if ($user->permissions()->count() > 0)
                            @foreach ($user->permissions as $perm)
                                {!! $perm->display_name !!}<br/>
                            @endforeach
                        @else
                            None
                        @endif
                    </td>
                    <td class="visible-lg">{!! $user->created_at->diffForHumans() !!}</td>
                    <td class="visible-lg">{!! $user->updated_at->diffForHumans() !!}</td>
                    <td>{!! $user->action_buttons !!}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="pull-left">
        {!! $users->total() !!} user(s) total
    </div>

    <div class="pull-right">
        {!! $users->render() !!}
    </div>

    <div class="clearfix"></div>
    {!! Form::close() !!}
@stop